# Generated by Django 3.2.7 on 2021-11-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_feedback_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
